#
#  Copyright (c) 2024 IONOS
#
#  This program and the accompanying materials are made available under the
#  terms of the Apache License, Version 2.0 which is available at
#  https://www.apache.org/licenses/LICENSE-2.0
#
#  SPDX-License-Identifier: Apache-2.0
#
#  Contributors:
#      IONOS
#

name: Build and publish maven artifacts

on:
  release:
    types: [published]

jobs:
  build-and-publish-artifacts:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
                
      - name: Set up JDK 17
        uses: actions/setup-java@v2
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Set version
        id: set-version
        run: echo "::set-output name=ref_name::${GITHUB_REF_NAME#v}"

      - name: Build project
        run: ./gradlew clean build
        env:
          EXTENSION_VERSION: ${{ steps.set-version.outputs.ref_name }}
          GITHUB_USER: ${{ github.actor }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Publish artifacts to GitHub Packages
        run: ./gradlew publish
        env:
          EXTENSION_VERSION: ${{ steps.set-version.outputs.ref_name }}
          GITHUB_USER: ${{ github.actor }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}